# Created by Jekyll Writer
title: "Sukhoi的独立博客"
description: "python使我快乐"
keyword: "Sukhoi, Life is short, I choose python"
url: ''
baseurl: ''
nav:
  home: /
  tags: /tags.html
footer:
  since: 2017
author: Sukhoi
nickname: ''
bio: "Python小菜鸡，保持激情"
avatar: /assets/img/profile.png
search: true
nightMode: true
comments:
  disqus: false
  disqus_url: 'https://liaokeyu.disqus.com/embed.js'
mathjax: true
social-share: true
social-share-items:
  - wechat
  - weibo
  - douban
  - twitter
theme-color: default
postPatterns: circuitBoard
sns:
  weibo: ''
  juejin: ''
  instagram: ''
  github: ''
recommend-tags: true
recommend-condition-size: 12
paginate: 10
paginate_path: 'page:num'
exclude:
  - node_modules
  - dev
  - package.json
  - gulpfile.js
  - .gitignore
  - README.md
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
RSS: false
permalink: '/:year/:month/:day/:title.html'
plugins:
  - jekyll-paginate
